// screens/SetAvailability.js
// Auto-generated by IBM Bob for User Story: KAN-10
// Redesign Tutor Profile Screen Using Modern Card-Based Layout

import React, { useState, useContext } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { AppContext } from '../context/AppContext';

export default function SetAvailability({ navigation }) {
  const { role } = useContext(AppContext);

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>Redesign Tutor Profile Screen Using Modern Card-Based Layout</Text>
      <Text style={styles.subtitle}>Feature implemented by IBM Bob</Text>
      <Text style={styles.desc}>Story: KAN-10</Text>
      <TouchableOpacity style={styles.btn} onPress={() => navigation.goBack()}>
        <Text style={styles.btnText}>Go Back</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, alignItems: 'center' },
  title:     { fontSize: 22, fontWeight: 'bold', marginBottom: 10, textAlign: 'center' },
  subtitle:  { fontSize: 14, color: '#666', marginBottom: 8 },
  desc:      { fontSize: 12, color: '#999', marginBottom: 20 },
  btn:       { backgroundColor: '#5c6bc0', padding: 14, borderRadius: 8, minWidth: 140, alignItems: 'center' },
  btnText:   { color: '#fff', fontWeight: '700', fontSize: 14 },
});
